backend:
  # name: test-repo # 测试专用 https://www.netlifycms.org/docs/test-backend/
  name: git-gateway # https://www.netlifycms.org/docs/git-gateway-backend/
  branch: main # 要更新的分支(可选；默认为主分支)

site_url: 'https://mikumi.netlify.app/'

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # 媒体文件将存储在图片/上载下的Repo中。
public_folder: "/images/uploads" # 上传的媒体的src属性将以/images/uploads开头。

locale: "zh_Hans" # 语言环境 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections:      # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "文章" # 在用户界面中使用
    folder: "source/_posts" # 存储文件的文件夹的路径。
    summary_fields:
      - date
      - title
    sortable_fields:
      fields:
        - date
        - title
      default:
        field: date
    create: true # 允许用户在这个集合中创建新的文件。
    fields: # 每份文件的字段，通常是前面的内容。
      - {label: "标题", name: "title", widget: "string" }
      - {label: "发布日期", name: "date", widget: "datetime", format: "yyyy-MM-dd HH:mm:ss", dateFormat: "yyyy-MM-dd", timeFormat: "HH:mm:ss", required: true}
      - {label: "作者", name: "author", widget: "hidden", default: MIKUMI}
      - {label: "文章顶置", name: "top", widget: "boolean", default: false}
      - {label: "显示侧边栏", name: "sidebar", widget: "boolean", default: true}
      - {label: "显示目录", name: "toc", widget: "boolean", default: true}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "分类", name: "categories", widget: "select", multiple: true, options: ['U盘', 'Inky', 'Arch', 'Other', '安科'], default: ['Other'], max: 1}
      - {label: "显示评论", name: "comments", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", required: false}
      - {label: "概述", name: "description", widget: "text", required: false}
      - {label: "内容", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "source/about/index.md"
        name: "about"
        label: "关于"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown", required: false}
          - {label: "评论", name: "comments", widget: "boolean", default: true, required: false}
